### ISSUE TITLE
What happens if I don't have docker installed on my machine?

### ISSUE THREAD

**Issue by akokkat** [IBMProjectEventStore/EventStore-DeveloperPreview#4]
What happens if I don't have docker installed on my machine?

**Comment by akokkat** [comment]
Docker gets automatically installed by Event Store if it not available on your machine.

**Comment by rafoid** [comment]
Yes, on some platforms it gets installed by EventStore automatically. If it can't be installed, you will get a list of prerequisites you have to fulfil before the installer can proceed.
